# Generated by Django 2.2.4 on 2021-04-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tech',
            field=models.BooleanField(default=False),
        ),
    ]
