# Generated by Django 2.2.4 on 2021-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier_climavenetta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chiller_uniflair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('compressor_one', models.BooleanField(blank=True, null=True)),
                ('compressor_two', models.BooleanField(blank=True, null=True)),
                ('compressor_three', models.BooleanField(blank=True, null=True)),
                ('compressor_four', models.BooleanField(blank=True, null=True)),
                ('eva_pressure_circuit_one', models.FloatField()),
                ('eva_pressure_circuit_two', models.FloatField()),
                ('cond_pressure_circuit_one', models.FloatField()),
                ('cond_pressure_circuit_two', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GE_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('battery_volt', models.FloatField()),
                ('hours_running', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GE_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('battery_volt', models.FloatField()),
                ('hours_running', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stulz_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stulz_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UPS_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volt_in_u', models.FloatField()),
                ('volt_in_v', models.FloatField()),
                ('volt_in_w', models.FloatField()),
                ('curr_in_u', models.FloatField()),
                ('curr_in_v', models.FloatField()),
                ('curr_in_w', models.FloatField()),
                ('frecuency_in', models.FloatField()),
                ('volt_out_u', models.FloatField()),
                ('volt_out_v', models.FloatField()),
                ('volt_out_w', models.FloatField()),
                ('curr_out_u', models.FloatField()),
                ('curr_out_v', models.FloatField()),
                ('curr_out_w', models.FloatField()),
                ('frecuency_out', models.FloatField()),
                ('battery_volt', models.FloatField()),
                ('battery_curr', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('last_event', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UPS_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volt_in_u', models.FloatField()),
                ('volt_in_v', models.FloatField()),
                ('volt_in_w', models.FloatField()),
                ('curr_in_u', models.FloatField()),
                ('curr_in_v', models.FloatField()),
                ('curr_in_w', models.FloatField()),
                ('frecuency_in', models.FloatField()),
                ('volt_out_u', models.FloatField()),
                ('volt_out_v', models.FloatField()),
                ('volt_out_w', models.FloatField()),
                ('curr_out_u', models.FloatField()),
                ('curr_out_v', models.FloatField()),
                ('curr_out_w', models.FloatField()),
                ('frecuency_out', models.FloatField()),
                ('battery_volt', models.FloatField()),
                ('battery_curr', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('last_event', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
