# Generated by Django 2.2.4 on 2021-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tek_view', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier_two',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Carrier_climavenetta',
            new_name='Carrier_one',
        ),
    ]
