# Generated by Django 2.2.4 on 2021-04-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tek_view', '0002_auto_20210423_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiller_climavenetta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_in', models.FloatField()),
                ('temp_out', models.FloatField()),
                ('compressor_one', models.BooleanField(blank=True, null=True)),
                ('compressor_two', models.BooleanField(blank=True, null=True)),
                ('compressor_three', models.BooleanField(blank=True, null=True)),
                ('compressor_four', models.BooleanField(blank=True, null=True)),
                ('eva_pressure_circuit_one', models.FloatField()),
                ('eva_pressure_circuit_two', models.FloatField()),
                ('cond_pressure_circuit_one', models.FloatField()),
                ('cond_pressure_circuit_two', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
